baseURL = 'https://monetr.app/'
languageCode = 'en-us'
title = 'monetr'
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true

[params.social]
github        = "monetr/monetr"
